### PR TITLE
Use Env for AWS region, fix 2.8 deprecation warnings

### PR DESCRIPTION
**Pull request by jmontleon**

### CODE REVIEW

**Comment by jmontleon** [comment]
@fbladilo FYI, this may affect CI wrt to using the environment variable for region.

**Comment by jmontleon** [comment]
Addresses https://github.com/fusor/origin3-dev/issues/37

**Review by eriknelson — APPROVED** [review]
Thanks Jason!

**Comment by jmontleon** [comment]
You're welcome. I'd just like to give Franco and @Danil-Grigorev  a chance to see it before merging so we don't break CI on them unexpectedly.

**Comment by eriknelson** [comment]
Yeah, that's why I didn't want to merge it right away. I'm certainly not
blocked by this, just thought it could be an improvement.

**Review by fbladilo — APPROVED** [review]
LGTM will update CI pipeline scripts to pass AWS_REGION

**Comment by jmontleon** [comment]
> LGTM will update CI pipeline scripts to pass AWS_REGION

Cool. Sounds good. I'll wait until at least Monday so you have a chance and then merge.

**Pull request merged**
